name: Lint Commit Messages

on:
  pull_request:
  push:

jobs:
  commitlint:
    if: github.actor != 'dependabot[bot]'

    runs-on: ubuntu-latest

    steps:
      - uses: step-security/harden-runner@1f99358870fe1c846a3ccba386cc2b2246836776 # 2.2.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443

      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # 3.5.3
        with:
          fetch-depth: 0

      - name: Lint
        uses: wagoid/commitlint-github-action@09faa1aae81627890cbffff1d0f7bc0e520a8b01 # 5.3.1
        with:
          configFile: package.json
          failOnWarnings: true
