name: Lint Commit Messages

on:
  pull_request:
  push:

jobs:
  commitlint:
    if: github.actor != 'dependabot[bot]'

    runs-on: ubuntu-latest

    steps:
      - uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # 2.4.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443

      - name: Checkout
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # 3.5.0
        with:
          fetch-depth: 0

      - name: Lint
        uses: wagoid/commitlint-github-action@09faa1aae81627890cbffff1d0f7bc0e520a8b01 # 5.3.1
        with:
          configFile: package.json
          failOnWarnings: true
