name: Test-Release

on:
  push:
    branches-ignore: [dependabot/**]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    name: test release

    runs-on: ubuntu-latest

    steps:
      - uses: step-security/harden-runner@18bf8ad2ca49c14cbb28b91346d626ccfb00c518 # 2.1.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            registry.npmjs.org:443
            registry.yarnpkg.com:443

      - name: Get branch name
        uses: tj-actions/branch-names@eee8675bd61ec38bcfbfedd504d8473292ba649e # 6.4
        id: branch-name

      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # 3.3.0

      - name: Install Node
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # 3.5.1
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Release Test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn semantic-release --dry-run --branches ${{ steps.branch-name.outputs.current_branch }}
